// Implementation file for parser generated by fsyacc
module Query.Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 3 "QueryParser.fsy"


open Query.Ast


# 12 "QueryParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | AND
  | OR
  | QUOTATION_MARK
  | LEFT_PAREN
  | RIGHT_PAREN
  | TERM of (System.String)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_AND
    | TOKEN_OR
    | TOKEN_QUOTATION_MARK
    | TOKEN_LEFT_PAREN
    | TOKEN_RIGHT_PAREN
    | TOKEN_TERM
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_UserQuery
    | NONTERM_SingleQuery
    | NONTERM_Phrase

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | AND  -> 1 
  | OR  -> 2 
  | QUOTATION_MARK  -> 3 
  | LEFT_PAREN  -> 4 
  | RIGHT_PAREN  -> 5 
  | TERM _ -> 6 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_AND 
  | 2 -> TOKEN_OR 
  | 3 -> TOKEN_QUOTATION_MARK 
  | 4 -> TOKEN_LEFT_PAREN 
  | 5 -> TOKEN_RIGHT_PAREN 
  | 6 -> TOKEN_TERM 
  | 9 -> TOKEN_end_of_input
  | 7 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_UserQuery 
    | 3 -> NONTERM_UserQuery 
    | 4 -> NONTERM_UserQuery 
    | 5 -> NONTERM_SingleQuery 
    | 6 -> NONTERM_SingleQuery 
    | 7 -> NONTERM_SingleQuery 
    | 8 -> NONTERM_SingleQuery 
    | 9 -> NONTERM_SingleQuery 
    | 10 -> NONTERM_Phrase 
    | 11 -> NONTERM_Phrase 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 9 
let _fsyacc_tagOfErrorTerminal = 7

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | AND  -> "AND" 
  | OR  -> "OR" 
  | QUOTATION_MARK  -> "QUOTATION_MARK" 
  | LEFT_PAREN  -> "LEFT_PAREN" 
  | RIGHT_PAREN  -> "RIGHT_PAREN" 
  | TERM _ -> "TERM" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | AND  -> (null : System.Object) 
  | OR  -> (null : System.Object) 
  | QUOTATION_MARK  -> (null : System.Object) 
  | LEFT_PAREN  -> (null : System.Object) 
  | RIGHT_PAREN  -> (null : System.Object) 
  | TERM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 5us; 65535us; 0us; 4us; 2us; 5us; 13us; 10us; 14us; 11us; 15us; 12us; 1us; 65535us; 7us; 8us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 11us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 3us; 1us; 2us; 4us; 1us; 2us; 3us; 3us; 7us; 8us; 3us; 4us; 7us; 8us; 1us; 5us; 1us; 6us; 2us; 6us; 11us; 1us; 6us; 3us; 7us; 7us; 8us; 3us; 7us; 8us; 8us; 3us; 7us; 8us; 9us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 9us; 1us; 10us; 1us; 11us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 8us; 10us; 14us; 18us; 20us; 22us; 25us; 27us; 31us; 35us; 39us; 41us; 43us; 45us; 47us; 49us; |]
let _fsyacc_action_rows = 19
let _fsyacc_actionTableElements = [|3us; 32768us; 3us; 7us; 4us; 15us; 6us; 6us; 0us; 49152us; 4us; 16385us; 0us; 3us; 3us; 7us; 4us; 15us; 6us; 6us; 0us; 16386us; 2us; 16387us; 1us; 13us; 2us; 14us; 2us; 16388us; 1us; 13us; 2us; 14us; 0us; 16389us; 1us; 32768us; 6us; 17us; 2us; 32768us; 3us; 9us; 6us; 18us; 0us; 16390us; 2us; 16391us; 1us; 13us; 2us; 14us; 2us; 16392us; 1us; 13us; 2us; 14us; 3us; 32768us; 1us; 13us; 2us; 14us; 5us; 16us; 3us; 32768us; 3us; 7us; 4us; 15us; 6us; 6us; 3us; 32768us; 3us; 7us; 4us; 15us; 6us; 6us; 3us; 32768us; 3us; 7us; 4us; 15us; 6us; 6us; 0us; 16393us; 0us; 16394us; 0us; 16395us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 10us; 11us; 14us; 17us; 18us; 20us; 23us; 24us; 27us; 30us; 34us; 38us; 42us; 46us; 47us; 48us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 2us; 1us; 2us; 1us; 3us; 3us; 3us; 3us; 1us; 2us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 3us; 3us; 3us; 3us; 3us; 4us; 4us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16386us; 65535us; 65535us; 16389us; 65535us; 65535us; 16390us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16393us; 16394us; 16395us; |]
let _fsyacc_reductions ()  =    [| 
# 118 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  Query.Ast.Query list )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 127 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'UserQuery)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "QueryParser.fsy"
                                        _1 
                   )
# 26 "QueryParser.fsy"
                 :  Query.Ast.Query list ));
# 138 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'UserQuery)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "QueryParser.fsy"
                                                _1 
                   )
# 29 "QueryParser.fsy"
                 : 'UserQuery));
# 149 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SingleQuery)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "QueryParser.fsy"
                                                [_1] 
                   )
# 30 "QueryParser.fsy"
                 : 'UserQuery));
# 160 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'UserQuery)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'SingleQuery)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "QueryParser.fsy"
                                                _2 :: _1 
                   )
# 31 "QueryParser.fsy"
                 : 'UserQuery));
# 172 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "QueryParser.fsy"
                                                               Term(_1)     
                   )
# 34 "QueryParser.fsy"
                 : 'SingleQuery));
# 183 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Phrase)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "QueryParser.fsy"
                                                               Phrase(_2)   
                   )
# 35 "QueryParser.fsy"
                 : 'SingleQuery));
# 194 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SingleQuery)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'SingleQuery)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "QueryParser.fsy"
                                                               And(_1, _3)  
                   )
# 36 "QueryParser.fsy"
                 : 'SingleQuery));
# 206 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SingleQuery)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'SingleQuery)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "QueryParser.fsy"
                                                               Or(_1, _3)   
                   )
# 37 "QueryParser.fsy"
                 : 'SingleQuery));
# 218 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'SingleQuery)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "QueryParser.fsy"
                                                               SubQuery(_2) 
                   )
# 38 "QueryParser.fsy"
                 : 'SingleQuery));
# 229 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "QueryParser.fsy"
                                      [_1] 
                   )
# 41 "QueryParser.fsy"
                 : 'Phrase));
# 240 "QueryParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Phrase)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "QueryParser.fsy"
                                      _2 :: _1 
                   )
# 42 "QueryParser.fsy"
                 : 'Phrase));
|]
# 253 "QueryParser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 10;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  Query.Ast.Query list  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
